### ISSUE TITLE
Problem when trying to generate shema in doctrine.

### ISSUE THREAD

**Issue by pbabilas** [myclabs/ACL#20]
Hi,

I've tried to generate db shema "php vendor/bin/doctrine orm:schema-tool:update" but no luck,

[Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'MyCLabs\ACL\Model\SecurityIdentityInterface' does not exist

There is problem processing Interface with class_exists ;> any idea?

**Comment by mnapoli** [comment]
That sounds like a problem with configuration or autoloading, have a look at the "setup" guide: http://myclabs.github.io/ACL/doc/setup.html
